import "./globals.css";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo List",
  description: "Generated by Nukrobzero",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} max-w-screen-xl mx-auto p-4 bg-slate-800 text-slate-100`}
      >
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
